# Configuration for robot_localization EKF node (Odom Instance)x
# Fuses odometry and IMU for odom->base_link transform and filtered odometry

ekf_filter_node_odom: # Node name must match the launch file
  ros__parameters:
    # GENERAL PARAMETERS
    frequency: 30.0                       # Target update frequency (Hz)
    sensor_timeout: 0.1                   # Sensor timeout in seconds before EKF stops using it
    two_d_mode: true                      # Robot operates in a 2D plane (important for surface boat)
    transform_time_offset: 0.0            # Apply a time offset to sensor data if needed
    transform_timeout: 0.0                # Timeout for TF lookups (0 = use latest available)
    print_diagnostics: true               # Publish diagnostic information

    # FRAME PARAMETERS
    map_frame: map                        # Not used by this instance, but must be set
    odom_frame: odom                      # Odometry frame (output frame for pose)
    base_link_frame: base_link            # Robot's base frame
    world_frame: odom                     # Specifies this instance provides continuous odometry data (odom->base_link)

    # TF PUBLICATION PARAMETERS
    publish_tf: true                      # Publish the odom->base_link transform
                                          # NOTE: This will override the TF from base_controller_node

    # ODOMETRY INPUT (from placeholder base_controller_node)
    odom0: /odom_raw                      # Topic name
    odom0_config:                         # Which variables to fuse (X, Y, Z, R, P, Y, Vx, Vy, Vz, Vroll, Vpitch, Vyaw, Ax, Ay, Az)
      [false, false, false,               # Don't fuse X, Y, Z pose from odom0 (let integration happen)
       false, false, false,               # Don't fuse Roll, Pitch, Yaw pose from odom0
       true,  false, false,               # Fuse Vx (linear X velocity), not Vy, Vz (assuming non-holonomic)
       false, false, true,                # Don't fuse Vroll, Vpitch, Fuse Vyaw (yaw rate)
       false, false, false]               # Don't fuse linear accelerations
    odom0_queue_size: 10                  # Input queue size
    odom0_nodelay: false                  # Allow slight delay
    odom0_differential: false             # Treat velocity data as absolute velocities in child frame (base_link)
    odom0_relative: false                 # Odometry is in the odom_frame

    # IMU INPUT (from placeholder_imu_node)
    imu0: /imu/data_raw                   # Topic name
    imu0_config:                          # Which variables to fuse
      [false, false, false,               # Don't fuse X, Y, Z pose
       false, false, false,               # Don't fuse Roll, Pitch, Yaw orientation (raw IMU often drifts badly)
       false, false, false,               # Don't fuse linear velocities
       true,  true,  true,                # Fuse Vroll, Vpitch, Vyaw (angular velocities are usually usable)
       false, false, false]               # Don't fuse linear accelerations (often noisy/biased)
    imu0_queue_size: 10                   # Input queue size
    imu0_nodelay: false                   # Allow slight delay
    imu0_differential: false              # Treat angular velocity as absolute rates
    imu0_relative: true                   # IMU data is relative to the base_link frame
    imu0_remove_gravitational_acceleration: true # Filter out gravity component from linear acceleration (good practice)

    # PROCESS NOISE COVARIANCE (How much uncertainty accumulates over time)
    # Tune these values based on real robot performance later
    # Format: Diagonal matrix for X, Y, Z, R, P, Y, Vx, Vy, Vz, Vr, Vp, Vy, Ax, Ay, Az
    process_noise_covariance: [0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,    # X
                               0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,    # Y
                               0.0,  0.0,  0.06, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,    # Z
                               0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,    # Roll
                               0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,    # Pitch
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.06, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,    # Yaw
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.025,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,    # Vx
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.025,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,    # Vy
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.04, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,    # Vz
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,    # Vroll
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,    # Vpitch
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.02, 0.0,  0.0,  0.0,    # Vyaw
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,    # Ax
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,    # Ay
                               0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.015]  # Az

    # INITIAL STATE COVARIANCE (How much uncertainty at the start)
    initial_estimate_covariance: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,      # X - Start with some uncertainty
                                  0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,      # Y
                                  0.0, 0.0, 1e-9, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,     # Z - Very certain in 2D mode
                                  0.0, 0.0, 0.0, 1e-9, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,     # Roll
                                  0.0, 0.0, 0.0, 0.0, 1e-9, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,     # Pitch
                                  0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,      # Yaw
                                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-9, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,     # Vx - Very certain initially zero
                                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-9, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,     # Vy
                                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-9, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,     # Vz
                                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-9, 0.0, 0.0, 0.0, 0.0, 0.0,     # Vroll
                                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-9, 0.0, 0.0, 0.0, 0.0,     # Vpitch
                                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-9, 0.0, 0.0, 0.0,     # Vyaw
                                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-9, 0.0, 0.0,     # Ax
                                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-9, 0.0,     # Ay
                                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-9]     # Az
